- hosts: all  # or group name
  become: true
  tasks: 
  # - name: Install apache
  #   include_tasks: apache.yml
  # - name: Install php
  #   include_tasks: php.yml
  # - name: Download wordpress
  #   include_tasks: wordpress.yml
  - name: Install mysql
    include_tasks: db.yml

